### PR TITLE
Fix search

### PR DESCRIPTION
**Pull request by Alan-Cha**
The problem seems to stem from a using a different version of jquery. I reverted back to the original version.

### CODE REVIEW

**Comment by Alan-Cha** [comment]
And the link checker action worked too!

**Comment by Alan-Cha** [comment]
Wait it stopped working again... hold on

**Comment by Alan-Cha** [comment]
@sriumcp It works locally but not in the preview. Could you clone my fork and try it locally as well? Sometimes it seems that the preview doesn't always work as intended...

**Review by sriumcp — APPROVED** [review]
LGTM.

**Pull request merged**
